# Generated by Django 5.2.4 on 2025-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichierCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="csv/")),
                ("date_import", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
